version: "3.7"

networks:
  demo-net:
    ipam:
      config:
        - subnet: 172.24.0.0/24

volumes:
  demo-db-volume:
  demo-master-index-volume:

services:
  db:
    container_name: db
    image: postgres:12.1-alpine
    networks:
      demo-net:
        ipv4_address: 172.24.0.10
    expose:
      - 5432
    environment:
      POSTGRES_DB: testcasedb
      POSTGRES_USER: testcasedbuser
      POSTGRES_PASSWORD: testcasedbpassword
    volumes:
      - demo-db-volume:/var/lib/postgresql/data
    restart: "no"

  app-master:
    container_name: app-master
    image: app-master:latest
    networks:
      demo-net:
        ipv4_address: 172.24.0.20
    volumes:
      - demo-master-index-volume:/mnt/master-index
    restart: "no"
    depends_on:
      - db

  app-slave:
    container_name: app-slave
    image: app-slave:latest
    networks:
      demo-net:
        ipv4_address: 172.24.0.21
    volumes:
      - demo-master-index-volume:/mnt/master-index
    restart: "no"
    depends_on:
      - db
      - app-master